# Tareas principales del rol odoo
---
- name: Inclule variables
  include_vars:
    dir: 'vars'

# Moved to the playbook as this role will be another container.
#- name: Include nginx role
  #include_role:
    #name: nginx
  #vars:
    #nginx_http_params: ["client_max_body_size 256M", "error_log /var/log/nginx/error.log"]

- name: Instalar dependencias comunes
  package: name={{item}} state=latest
  with_items:
    - git
    - xauth
    - python-pip
    - python-cups
    - python-jinja2
    - python-unicodecsv
    - python-psycopg2
    - python-simplejson
    - python-lxml
    - python-imaging
    - python-yaml
    - python-reportlab
    - python-mako
    - python-werkzeug
    - python-dateutil
    - python-unittest2
    - python-mock
    - python-openid
    - python-docutils
    - python-feedparser
    - python-psutil
    - python-pydot
    - python-vatnumber
    - python-vobject
    - python-xlwt
    - python-ldap
    - python-requests
    - python-decorator
    - python-passlib
    - python-babel
    - python-gevent

- name: Install Odoo dependencies for CentOS
  package: name={{item}} state=latest
  with_items:
    - python-devel
    - babel
    - libxslt
    - pychart
    - pyparsing
    - pytz
    - pyOpenSSL
    - python-inotify
    - python-GeoIP
    - pyPdf
      # buscar para centos
    #- python-pyparsing
    #- python-zsi
    #- xfonts-utils
    #- xfonts-base
    #- python-apt
    #- xfonts-75dpi
  when: ansible_distribution == 'CentOS'

- name: Install Odoo dependencies Ubuntu
  package: name={{item}} state=latest
  with_items:
    - python-webdav
    - python-gdata
    - xfonts-75dpi
    - python-apt
    - xfonts-base
    - python-pyparsing
    - xfonts-utils
    - python-dev
    - python-libxslt1
    - python-psycopg2
    - python-geoip
    - python-pybabel
    - python-pyinotify
    - python-tz
    - python-pychart
    - python-openssl
    - python-egenix-mxdatetime
    - python-pypdf
    # OJO, creo que en ubuntu < 16 no está pypdf2 en los repos.
    - python-pypdf2
    - python-babel
    - python-zsi
  when: ansible_distribution == 'Ubuntu'


# TODO: condicionar según arquitectura y sistema operativo
- name: Instalar wkhtmltopdf en Ubuntu 64 bits
  action: apt deb=http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
  when: ansible_distribution == 'Ubuntu'

  # TODO: la condición de version == '7' parece no cumplirse
- name: Instalar wkhtmltopdf en Centos7
  yum:
    name: http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-centos7-amd64.rpm
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '7'

- name: Instalar locale para el sistema
  locale_gen: name=es_ES.UTF-8 state=present
  when: ansible_distribution == 'Ubuntu'

- name: Instalar dependencias pip
  pip: name={{ item }}
  with_items: 
    - openupgradelib
    - unidecode
    - psycogreen
    - xlrd

- name: Dependencias pip adicionales para CentOS
  pip: name={{ item }}
  with_items: 
    - gdata
    - pywebdav
    - egenix-mx-base
  when: ansible_distribution == 'CentOS'

#- name: Instalar postgres
  #package: name={{item}} state=latest
  #with_items:
    #- postgresql

- name: Add Odoo system user
  user: name={{ odoo_user }} shell=/bin/bash
        password={{ odoo_user_passwd }} update_password=on_create
  tags:
    - odoo
    - odoo_user

- name: Add ansible user to odoo system user group
  user: name={{ ansible_user }}
        groups={{ odoo_user }}
        append=yes
  tags:
    - odoo_user

- name: Create log directory
  file: path={{ odoo_logdir }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} force=no
  tags:
    - odoo
    - odoo_log

- name: Project repository exists? (Mercurial)
  stat: path={{ odoo_repo_dest }}
  register: project_path
  tags:
    - odoo
    - odoo_project

- name: Clone project repository (Git)
  git:  repo={{ odoo_repo_url }}
        dest={{ odoo_repo_dest }}
        version={{ odoo_repo_rev }}
        update=no
        force=no
        depth=1
  when: odoo_repo_type == 'git' and odoo_repo_url
  tags:
    - core

- name: Cambiar propietario del directorio
  file: path={{ odoo_workdir }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} recurse=yes
  tags:
    - core

- name: Repositorios oca
  include: reposoca.yml
  tags:
    - repos
    - reposoca

- name: Repositorios instancia
  include: reposinstancia.yml
  tags:
    - repos
    - reposinstancia

# [ ODOO 8.0 ]
- name: Create config directory
  file: path={{ odoo_config_path }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} force=no
  tags:
    - config
    - repos
    - reposoca
    - reposinstancia

- name: Copy Odoo configuration file (8.0)
  template: src=odoo-server-v80.conf dest={{ odoo_config_file }}
        owner={{ odoo_user }} group={{ odoo_user }} mode=0640
        force={{ odoo_force_config and 'yes' or 'no' }}
        backup=yes
  when: odoo_version == 8.0
  tags:
    - config
    - repos
    - reposoca
    - reposinstancia

- name: Copy Odoo init script (8.0)
  template: src=odoo-server-v80.init dest=/etc/init.d/{{ odoo_service }}
        owner=root group=root mode=0755
        force={{ odoo_force_config and 'yes' or 'no' }}
        backup=yes
  when: odoo_version == 8.0
  tags:
    - odoo
    - odoo_config

# [/ ODOO 8.0 ]

# - name: Set SSH public keys for the Odoo user
#   authorized_key: user={{ odoo_user }}
#                   key="{{ lookup('file', item) }}"
#   with_fileglob:
#     - "{{ odoo_user_sshkeys }}"
#   when: odoo_user_sshkeys is defined and odoo_user_sshkeys
#   tags:
#     - odoo
#     - odoo_ssh

#- name: Postgres tasks
  #include: postgres.yml

- include: servicios.yml
