---
- name: Incluir variables del rol
  include_vars:
    dir: 'vars'

- name: Rol de nginx
  include_role:
    name: nginx
  vars:
    nginx_http_params: ["client_max_body_size 256M", "error_log /var/log/nginx/error.log"]

- name: Install Odoo dependencies
  action: apt pkg=git,python-dev,xfonts-utils,python-cups,python-jinja2,python-unicodecsv,python-pyparsing,python-libxslt1,python-psycopg2,python-geoip,xfonts-base,python-apt,xfonts-75dpi,python-pybabel,python-simplejson,python-lxml,python-pyinotify,python-tz,python-imaging,python-yaml,python-reportlab,python-mako,python-pychart,python-werkzeug,python-dateutil,python-unittest2,python-mock,python-openid,python-docutils,python-feedparser,python-gdata,python-jinja2,python-psutil,python-pydot,python-webdav,python-vatnumber,python-vobject,python-xlwt,python-ldap,python-openssl,python-egenix-mxdatetime,python-zsi,python-requests,python-pypdf,python-decorator,python-passlib,python-babel,python-gevent
          state=installed
          update_cache=yes
  tags:
    - odoo
    - odoo_packages

- name: Instalar wkhtmltopdf
  action: apt deb=http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
- name: Install common tools
  action: apt pkg=xauth,python-pip
          state=installed install_recommends=yes
  tags:
    - odoo
    - odoo_packages

#- name: Eliminar locale con LATIN para evitar problemas.
  #locale_gen: name=en_US.ISO-8859-1 state=absent

- name: Instalar locale para el sistema
  locale_gen: name=es_ES.UTF-8 state=present

- name: Instalar openupgradelib (dependencia pip de odoomrp-wip)
  pip: name=openupgradelib

- name: Instalar unidecode (pip)
  pip: name=unidecode

- name: Install Odoo dependencies (from PyPi)
  pip: name=psycogreen
  tags:
    - odoo
    - odoo_packages


- name: Instalar postgres
  apt: pkg=postgresql state=installed
  tags:
    - odoo
    - odoo_packages

- name: Add Odoo system user
  user: name={{ odoo_user }} shell=/bin/bash
        password={{ odoo_user_passwd }} update_password=on_create
  tags:
    - odoo
    - odoo_user

- name: Create log directory
  file: path={{ odoo_logdir }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} force=no
  tags:
    - odoo
    - odoo_log

- name: Project repository exists? (Mercurial)
  stat: path={{ odoo_repo_dest }}
  register: project_path
  tags:
    - odoo
    - odoo_project

- name: Clone project repository (Git)
  git:  repo={{ odoo_repo_url }}
        dest={{ odoo_repo_dest }}
        version={{ odoo_repo_rev }}
        update=no
        force=no
        depth=1
  when: odoo_repo_type == 'git' and odoo_repo_url
  tags:
    - odoo
    - odoo_project

- name: Cambiar propietario del directorio
  file: path={{ odoo_workdir }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} recurse=yes

- name: Repositorios OCA
  include: reposoca.yml

# [ ODOO 8.0 ]
- name: Create config directory
  file: path={{ odoo_config_path }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} force=no
  tags:
    - odoo
    - odoo_log

- name: Copy Odoo configuration file (8.0)
  template: src=odoo-server-v80.conf dest={{ odoo_config_file }}
        owner={{ odoo_user }} group={{ odoo_user }} mode=0600
        force={{ odoo_force_config and 'yes' or 'no' }}
        backup=yes
  when: odoo_version == 8.0
  tags:
    - odoo
    - odoo_config

- name: Copy Odoo init script (8.0)
  template: src=odoo-server-v80.init dest=/etc/init.d/{{ odoo_service }}
        owner=root group=root mode=0755
        force={{ odoo_force_config and 'yes' or 'no' }}
        backup=yes
  when: odoo_version == 8.0
  tags:
    - odoo
    - odoo_config

# [/ ODOO 8.0 ]

# - name: Set SSH public keys for the Odoo user
#   authorized_key: user={{ odoo_user }}
#                   key="{{ lookup('file', item) }}"
#   with_fileglob:
#     - "{{ odoo_user_sshkeys }}"
#   when: odoo_user_sshkeys is defined and odoo_user_sshkeys
#   tags:
#     - odoo
#     - odoo_ssh

- name: Postgres tasks
  include: postgres.yml

- include: servicios.yml
