---

# - name: Remote PostgreSQL - Add the Odoo user
#   delegate_to: "{{ odoo_config_db_host }}"
#   remote_user: "{{ odoo_config_db_host_user }}"
#   sudo: yes
#   sudo_user: postgres
#   postgresql_user: name={{ odoo_config_db_user }}
#                    role_attr_flags=CREATEDB,NOSUPERUSER
#   when: odoo_config_db_host not in [False, 'localhost', '127.0.0.1']
#   tags:
#     - odoo
#     - odoo_postgresql

- name: Local PostgreSQL - Add the Odoo user
  become: true
  become_user: postgres
  postgresql_user: name={{ odoo_config_db_user }}
                   role_attr_flags=CREATEDB,NOSUPERUSER
  when: odoo_config_db_host in [False, 'localhost', '127.0.0.1']
  tags:
    - odoo
    - odoo_postgresql

# - name: Remote PostgreSQL - Set the Odoo user password
#   delegate_to: "{{ odoo_config_db_host }}"
#   remote_user: "{{ odoo_config_db_host_user }}"
#   sudo: yes
#   sudo_user: postgres
#   postgresql_user: name={{ odoo_config_db_user }}
#                    password={{ odoo_config_db_passwd }}
#   when: odoo_config_db_host not in [False, 'localhost', '127.0.0.1']
#         and odoo_config_db_passwd is defined and odoo_config_db_passwd
#   tags:
#     - odoo
#     - odoo_postgresql

- name: Local PostgreSQL - Set the Odoo user password
  become: true
  become_user: postgres
  postgresql_user: name={{ odoo_config_db_user }}
                   password={{ odoo_config_db_passwd }}
  when: odoo_config_db_host in [False, 'localhost', '127.0.0.1']
        and odoo_config_db_passwd is defined and odoo_config_db_passwd
  tags:
    - odoo
    - odoo_postgresql

# Crear bases de datos. Esto lo comentamos porque vamos a importar un backup.
- name: Local PostgreSQL - Create databases
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ odoo_config_db_user }}"
    encoding: 'UTF-8'
    lc_collate: "{{ item.locale}}"
    lc_ctype: "{{ item.locale }}"
    # TODO: confirmar que es este template, ojo.
    template: "template0"
    state: present
  with_items: "{{ odoo_databases }}"
  when: odoo_config_db_host in [False, 'localhost', '127.0.0.1']
  tags:
    - odoo
    - odoo_postgresql

# - name: Remote PostgreSQL - Active the 'unaccent' extension on databases
#   delegate_to: "{{ odoo_config_db_host }}"
#   remote_user: "{{ odoo_config_db_host_user }}"
#   sudo: yes
#   sudo_user: postgres
#   shell: "psql {{ item.name }} -c 'CREATE EXTENSION IF NOT EXISTS \"unaccent\";'"
#   with_items: odoo_databases
#   when: odoo_config_db_host not in [False, 'localhost', '127.0.0.1']
#         and odoo_config_unaccent
#   changed_when: False
#   tags:
#     - odoo
#     - odoo_postgresql

- name: Local PostgreSQL - Active the 'unaccent' extension on databases
  shell: "psql {{ item.name }} -c 'CREATE EXTENSION IF NOT EXISTS \"unaccent\";'"
  with_items: "{{ odoo_databases }}"
  changed_when: False
  when: odoo_config_db_host in [False, 'localhost', '127.0.0.1']
        and odoo_config_unaccent
  tags:
    - odoo
    - odoo_postgresql
