# Tarea para los repositorios del servidor de ledyspa
# TODO: incluir el atributo depth en los repositorios para ahorrar BASTANTE ESPACIO
#     Parece que si se indica el depth después de que el repo ya exista da error:
#     fatal: [ledyspa]: FAILED! => {"changed": false, "cmd": ["/usr/bin/git", "fetch",
#             "--depth", "1", "origin", "+refs/heads/8.0:refs/heads/8.0"],
#             "failed": true, "msg": "Failed to download remote objects and refs:
#             fatal: Refusing to fetch into current branch refs/heads/8.0 of non-bare
#             repository\nUnexpected end of command stream\n"}

# TODO: estos repositorios deberían tener alguna relación directa con el addons_path
#   que configuramos para cada servidor.

# TODO: Poner un name a los repos o esto es una mierda en el output de ansible
---
- name: Repo acysos
  git: repo=https://github.com/acysos/odoo-addons.git dest=/opt/Upgrade/common/acysos version=8.0

- name: Repo web de la OCA
  git:
    repo=https://github.com/OCA/web.git
    dest=/opt/common/addons/web
    version=8.0

- name: Repo rma de la OCA
  git:
    repo=https://github.com/OCA/rma.git
    dest=/opt/common/addons/rma
    version=8.0

- name: Repo reporting-engine de la OCA
  git:
    repo=https://github.com/OCA/reporting-engine.git
    dest=/opt/common/addons/reporting-engine
    version=8.0

- name: Repo product-attribute de la OCA
  git:
    repo=https://github.com/OCA/product-attribute.git
    dest=/opt/common/addons/product-attribute
    version=8.0

- name: Repo pos de la OCA
  git:
    repo=https://github.com/OCA/pos.git
    dest=/opt/common/addons/pos
    version=8.0

- name: Repo partner-contact de la OCA
  git:
    repo=https://github.com/OCA/partner-contact.git
    dest=/opt/common/addons/partner-contact
    version=8.0

- name: Repo odoomrp-wip
  git:
    repo=https://github.com/odoomrp/odoomrp-wip.git
    dest=/opt/common/addons/odoomrp-wip
    version=8.0

- name: Repo multi-company de la OCA
  git:
    repo=https://github.com/OCA/multi-company.git
    dest=/opt/common/addons/multi-company
    version=8.0

- name: Repo manufacture de la OCA
  git:
    repo=https://github.com/OCA/manufacture.git
    dest=/opt/common/addons/manufacture
    version=8.0

- name: Repo management-system de la OCA
  git:
    repo=https://github.com/OCA/management-system.git
    dest=/opt/common/addons/management-system
    version=8.0

- name: Repo commission de la OCA
  git:
    repo=https://github.com/OCA/commission.git
    dest=/opt/Upgrade/common/commission
    version=8.0

- name: Repo purchase-workflow de la OCA
  git:
    repo=https://github.com/OCA/purchase-workflow.git
    dest=/opt/Upgrade/common/purchase-workflow
    version=8.0

- name: Repo sale-workflow de la OCA
  git:
    repo=https://github.com/OCA/sale-workflow.git
    dest=/opt/Upgrade/common/sale-workflow
    version=8.0

- name: Repo stock-logistics-warehouse de la OCA
  git:
    repo=https://github.com/OCA/stock-logistics-warehouse.git
    dest=/opt/Upgrade/common/stock-logistics-warehouse
    version=8.0

- name: Repo stock-logistics-workflow de la OCA
  git:
    repo=https://github.com/OCA/stock-logistics-workflow.git
    dest=/opt/Upgrade/common/stock-logistics-workflow
    version=8.0

- name: Repo account-financial-reporting de la OCA
  git:
    repo=https://github.com/OCA/account-financial-reporting
    dest=/opt/common/addons/account-financial-reporting
    version=8.0

- name: Repo de account-financial-tools de la OCA
  git:
    repo=https://github.com/OCA/account-financial-tools.git
    dest=/opt/common/addons/account-financial-tools
    version=8.0

- name: Repo account-invoice-reporting de la OCA
  git:
    repo=https://github.com/OCA/account-invoice-reporting.git
    dest=/opt/common/addons/account-invoice-reporting
    version=8.0

- name: Repo account-invoicing de la OCA
  git:
    repo=https://github.com/OCA/account-invoicing.git
    dest=/opt/common/addons/account-invoicing
    version=8.0

- name: Repo account-payment de la OCA
  git:
    repo=https://github.com/OCA/account-payment.git
    dest=/opt/common/addons/account-payment
    version=8.0

- name: Repo bank-payment de la OCA
  git:
    repo=https://github.com/OCA/bank-payment.git
    dest=/opt/common/addons/bank-payment
    version=8.0

- name: Repo bank-statement-import de la OCA
  git:
    repo=https://github.com/OCA/bank-statement-import.git
    dest=/opt/common/addons/bank-statement-import
    version=8.0

- name: Repo crm de la OCA
  git:
    repo=https://github.com/OCA/crm.git
    dest=/opt/common/addons/crm
    version=8.0

- name: Repo knowledge de la OCA
  git:
    repo=https://github.com/OCA/knowledge.git
    dest=/opt/common/addons/knowledge
    version=8.0

- name: Repo de la localización española (OCA)
  git:
    repo=https://github.com/OCA/l10n-spain.git
    dest=/opt/common/addons/l10n-spain
    version=8.0

- name: Repo de herramientas de servidor de la OCA
  git:
    repo=https://github.com/OCA/server-tools.git
    dest=/opt/common/addons/server-tools
    version=8.0

#     "/opt/common/addons/ledyspa": "https://gonxi@bitbucket.org/gonxi/ledyspa.git",
# Este repositorio necesita una llave privada, la ubicación es relativa al
# equipo en el que se va a instalar el repositorio.


- name: Copiar la llave de deploy de Bitbucket
  copy: src="/home/ruben/.ssh/ledyspa_test.pub"
        dest=/home/odoo/.ssh/ledyspa_test.pub
        mode=0644
        owner=odoo
        group=odoo

- name: Llave privada para deploy
  copy: src="/home/ruben/.ssh/ledyspa_test"
        dest=/home/odoo/.ssh/ledyspa_test
        mode=0600
        owner=odoo
        group=odoo

- name: Repo privado de ledyspa (bitbucket)
  git:
    repo=git@bitbucket.org:gonxi/ledyspa.git
    dest=/opt/common/addons/ledyspa
    key_file=/home/odoo/.ssh/ledyspa_test
    accept_hostkey=True

- name: Repo bank-statement-reconcile de la OCA
  git:
    repo=https://github.com/OCA/bank-statement-reconcile.git
    dest=/opt/common/addons/bank-statement-reconcile
    version=8.0

- name: Cambiar propietario del directorio common
  file: path=/opt/common state=directory
        owner={{ odoo_user }} group={{ odoo_user }} recurse=yes
# El directorio Upgrade hace falta aquí o es fruto de un lío?
- name: Cambiar propietario del directorio Upgrade
  file: path=/opt/Upgrade state=directory
        owner={{ odoo_user }} group={{ odoo_user }} recurse=yes
