# Tareas para la creación y gestión de los repositorios de la comunidad.
---

- name: Directorio repositorios oca
  file: path={{ path_repos_oca }} state=directory
  tags:
    - reposoca

- name: Clonar repsitorios oca
  git:
    repo: "{{ item.url }}" 
    depth: 1 
    dest: "{{ path_repos_oca }}/{{ item.name }}" 
    version: "8.0"
    # Metido porque si no tenemos errores por los pyc
    force: yes
  with_items: "{{ repositorios_oca }}"
  tags:
    - reposoca
    - repos

- name: Permisos repositorios
  file: path={{ path_repos_oca }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} recurse=yes
  tags:
    - reposoca
    - repos
