# Configura los servicios de odoo. Ejecutar después de main y de postgres. 
---

- name: Set Odoo service runlevels
  command: update-rc.d {{ odoo_service }} defaults
  changed_when: False
  tags:
    - servicio
    - odoo_init

- name: Enable Odoo service
  service: name={{ odoo_service }} enabled=yes
  when: odoo_init == True
  tags:
    - servicio
    - odoo_init

- name: Disable Odoo service
  service: name={{ odoo_service }} enabled=no
  when: odoo_init == False
  tags:
    - servicio
    - odoo_init

- name: Restart odoo service
  service: name={{ odoo_service }} state=restarted
  when: odoo_init == True
  tags:
    - odoo_restart
    - repos
    - reposoca
    - reposinstancia
